### ISSUE TITLE
it does not bench fib5 from tfib example

### ISSUE THREAD

**Issue by inv2004** [disruptek/criterion#1]
Hello,

I was trying to compile https://github.com/disruptek/criterion.nim/blob/master/tests/tfib.nim

I expected: to have fib5, fibN and fibN1 benchmarks
But it outputs finN and fibN1 without fib5

nim: 1.0.4 [Windows]

**Comment by inv2004** [comment]
Workaround:
```nim
proc fib5() {.measure:[].} =
```

**Comment by disruptek** [comment]
Yeah, I looked at this and it appears to be an issue with Nim's `pragma` macro.  I know, nuts.  I need to debug it further...

**Comment by disruptek** [comment]
Fixed in 0.1.1.
