### ISSUE TITLE
suggestion: reduce samples when NIM_TEST_PACKAGES exists

### ISSUE THREAD

**Issue by bung87** [disruptek/criterion#2]
I notice GitHub CI for nim repo consuming 184.37 secs  

ubuntu-18.04 (pkg: 1)
criterion C                                                  (184.37 sec)

**Comment by disruptek** [comment]
We arrived at this runtime as a compromise for the compiler.  If you have an elegant compromise like `compiler.nims`, feel free to make a PR.

**Comment by disruptek** [comment]
Closed in 0.2.4.
